version: "2"

services:
  car-bug-scanner:
    restart: always
    env_file:
      - ../.env
    build:
      context: ../
      dockerfile: ./docker/app/Dockerfile
    ports:
      - "8000:8000"
    volumes: 
      - ../:/home/python/app
    networks:
      proxy:
        ipv4_address: 172.19.0.9
    stdin_open: true # docker run -i
    tty: true        # docker run -t

networks:
  proxy:
    name: proxy
    external: true
